In [1]:
import numpy as np
import tensorflow as tf

In [3]:
print("Setting Eager mode...")
tf.enable_eager_execution()
tfe = tf.contrib.eager

Setting Eager mode...


In [4]:
a = tf.constant(2)
b = tf.constant(3)

print(a)
print(b)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


In [5]:
c = a+b
d = a*b
print(c)
print(d)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


In [6]:
a = tf.constant([[2., 1.],
                 [1., 0.]], dtype = tf.float32)
b = np.array([[3., 0.],
              [5., 1.]], dtype = np.float32)

print(a)
print(b)

tf.Tensor(
[[2. 1.]
 [1. 0.]], shape=(2, 2), dtype=float32)
[[3. 0.]
 [5. 1.]]


In [7]:
c = a+b
d = tf.matmul(a,b)

print(c)
print(d)

tf.Tensor(
[[5. 1.]
 [6. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[11.  1.]
 [ 3.  0.]], shape=(2, 2), dtype=float32)


In [9]:
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        print(a[i][j])

tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
